web:
  build: .
  command: "bash -c 'Executable --env=staging --workdir=/app/ --config:servers.default.port=$PORT --config:postgresql.url=$DATABASE_URL --config:apns.topic=$APNS_TOPIC --config:apns.teamId=$APNS_TEAM_ID --config:apns.keyId=$APNS_KEY_ID'"
  working_dir: /app/
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
shell:
  build: .
  command: bash
  working_dir: /app/
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
